runtime: python39
instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "true"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT app:app 